export const FETCHING_START = 'FETCHING_START';
export const FETCHING_SUCCESS = 'FETCHING_SUCCESS';
export const FETCHING_ERROR = 'FETCHING_ERROR';
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';


// export const actionTypes = {
//     FETCHING_START: 'FETCHING_START',
//     FETCHING_SUCCESS : 'FETCHING_SUCCESS',
//     FETCHING_ERROR : 'FETCHING_ERROR',
//     ADD_TO_CART : 'ADD_TO_CART',
//     ADD_TO_WISHLIST : 'ADD_TO_WISHLIST',
// };